# Proje Tanimi

#### Proje Amaci
Bu proje; NumPy array mantığını, metodları ve dizi işlemlerini kullanarak **gerçekçi bir satış verisi analizi** yapmayı hedefler.

#### Numpy Neden Kullanilir?
NumPy, Python’da özellikle sayısal işlemleri hızlı ve verimli yapmak için kullanılır.

* Büyük sayı dizileriyle (array) çalışmayı sağlar
* Matematiksel işlemleri çok hızlı yapar
* Bilimsel hesaplamaların temelini oluşturur

#### Kullanilan Numpy Konulari
* Array oluşturma
* Array özellikleri (shape, ndim, dtype)
* Indexing & slicing
* sum, mean, max, min
* axis kullanımı
* reshape, transpose, flatten

In [99]:
# Importing Numpy and creating data
import numpy as np

# random sales matrix(7*5)
sales = np.random.randint(50, 200, size=(7, 5))
sales

array([[147,  73,  83,  93, 109],
       [114, 151, 170, 101,  91],
       [134,  87,  75, 101, 106],
       [ 66, 183, 161, 124, 184],
       [197, 131,  96,  52,  69],
       [175, 134, 128,  77,  72],
       [ 56,  85, 163,  93, 147]])

In [93]:
# Arrays
shape_of_sales = sales.shape
dim_of_sales = sales.ndim
type_of_sales = sales.dtype
size_of_sales = sales.size

print(f"shapeof sales: {shape_of_sales}")
print(f"dimension of sales: {dim_of_sales}")
print(f"type of sales: {type_of_sales}")
print(f"size of sales: {size_of_sales}")



shapeof sales: (7, 5)
dimension of sales: 2
type of sales: int64
size of sales: 35


In [94]:
#Indexing and slicing
first_day_of_sales = sales[0]
second_product_weekly_sales = sales[:,2]
first_three_day_of_sales = sales[:3]

print(f"Sales for 1th day: {first_day_of_sales}")
print(f"Weekly sales for 2nd product: {second_product_weekly_sales}")
print(f"Sales for first 3 day: {first_three_day_of_sales}")


Sales for 1th day: [116  59  56  94  66]
Weekly sales for 2nd product: [ 56  76 170 149 197 182  64]
Sales for first 3 day: [[116  59  56  94  66]
 [110  50  76 123 177]
 [168 157 170  83  73]]


In [95]:
# Basic Numpy Methods
total_sales = sales.sum()
avg_sale = sales.mean()
max_sale = sales.max()
min_sale = sales.min()

print(f"Total sales: {total_sales}")
print(f"Average sale: {avg_sale}")
print(f"Max sale: {max_sale}")
print(f"Min sale: {min_sale}")

Total sales: 4137
Average sale: 118.2
Max sale: 197
Min sale: 50


In [96]:
# Using Axis
total_for_weekly_product_sales = sales.sum(axis=0)
total_for_daily_product_sales = sales.sum(axis=1)

# axis = 0 -> sütunlar boyunca islem yapar
# axis = 1 -> satirlar boyunca islem yapar

In [97]:
# Numpy array methods
reshaped_sales = sales.reshape(5,7)
transposed_sales = sales.T
flatted_sales = sales.flatten()
# ravel_sales = sales.ravel()

print(f"Reshaped sales: {reshaped_sales}")
print(f"Transposed sales: {transposed_sales}")

Reshaped sales: [[116  59  56  94  66 110  50]
 [ 76 123 177 168 157 170  83]
 [ 73 186  61 149  91  61 142]
 [ 70 197 105 134  87 122 182]
 [139 186 140 121  64 169 153]]
Transposed sales: [[116 110 168 186 142  87 140]
 [ 59  50 157  61  70 122 121]
 [ 56  76 170 149 197 182  64]
 [ 94 123  83  91 105 139 169]
 [ 66 177  73  61 134 186 153]]


In [102]:
# Outputs
best_sale_product_index = total_for_daily_product_sales.argmax() + 1
best_sale_day_index = total_for_weekly_product_sales.argmax() + 1


print(f"Weekly Total Sale: {total_sales}")
print(f"Best Sale Product: product {best_sale_product_index}")
print(f"Best Sale Day: day {best_sale_day_index}")

Weekly Total Sale: 4137
Best Sale Product: product 6
Best Sale Day: day 1
