## Projenin Amaci
Bir şirketin 8 çalışana ait 6 aylık performans skorları NumPy ile analiz edilecektir.
## NumPy Neden Kullanilir?
NumPy'in kullanim amaclari:

* Hızlı sayısal hesaplama yapmak için
* Büyük veri dizileriyle (array/matris) çalışmak için
* Matematiksel işlemleri döngüsüz ve performanslı yapmak için
* Lineer cebir ve bilimsel hesaplamalar için
* Veri bilimi ve makine öğrenmesinin temelini oluşturmak için

## Kapsanan NumPy Konulari
Bu projede **yalnızca** aşağıdaki NumPy konuları kullanılacaktır:

- NumPy giriş
- NumPy array oluşturma
- NumPy metodları
- NumPy dizi (array) metodları
- NumPy indeksleme
- Matrix indeksleme
- NumPy operasyonlar (vektörel işlemler)


In [54]:
# 2. Importing numPy and creating a random performance matrix(8x6)
import numpy as np
from numpy.ma.core import argmax

performance_matrix = np.random.randint(0,100, size=(8,6))
print(performance_matrix)

[[56 25 74 45  7 98]
 [82  6 22 49  5  5]
 [ 3 63 96 38 10 53]
 [92 20 17 57 21 11]
 [16 59 40 92 65 94]
 [72 52 97  8 97  5]
 [80 41 52 84 76 81]
 [66 93 91 62 11 17]]


In [55]:
# 3. shape, ndim and dtype
shape_of_matrix = performance_matrix.shape
ndim_of_matrix = performance_matrix.ndim
type_of_matrix = performance_matrix.dtype

print(shape_of_matrix)
print(ndim_of_matrix)
print(type_of_matrix)

(8, 6)
2
int64


In [56]:
# 4. Indexing in NumPy
first_employee_all_months = performance_matrix[0]
last_month_all_employees = performance_matrix[:,-1]
first_three_employees_first_two_months = performance_matrix[:3, :2]

print(first_employee_all_months)
print(last_month_all_employees)
print(first_three_employees_first_two_months)

[56 25 74 45  7 98]
[98  5 53 11 94  5 81 17]
[[56 25]
 [82  6]
 [ 3 63]]


In [57]:
# 5. Indexing matrix
employee_index = 3
month_index = 5

performance_score = performance_matrix[employee_index, month_index]

sub_matrix = performance_matrix[:3, :4]

print(f"5th month score of 3rd Employee: {performance_score}")
print(sub_matrix)

5th month score of 3rd Employee: 11
[[56 25 74 45]
 [82  6 22 49]
 [ 3 63 96 38]]


In [58]:
# 6. Adding 5 points to all scores
adding_5_points_to_all_scores = performance_matrix + 5
normalizing_all_scores = performance_matrix / 100

# Comparing 3rd and 5th month scores
month4 = performance_matrix[:, 3]
month5 = performance_matrix[:, 4]

comp = (month5 > month4)

print(adding_5_points_to_all_scores)
print(normalizing_all_scores)
print(comp)

[[ 61  30  79  50  12 103]
 [ 87  11  27  54  10  10]
 [  8  68 101  43  15  58]
 [ 97  25  22  62  26  16]
 [ 21  64  45  97  70  99]
 [ 77  57 102  13 102  10]
 [ 85  46  57  89  81  86]
 [ 71  98  96  67  16  22]]
[[0.56 0.25 0.74 0.45 0.07 0.98]
 [0.82 0.06 0.22 0.49 0.05 0.05]
 [0.03 0.63 0.96 0.38 0.1  0.53]
 [0.92 0.2  0.17 0.57 0.21 0.11]
 [0.16 0.59 0.4  0.92 0.65 0.94]
 [0.72 0.52 0.97 0.08 0.97 0.05]
 [0.8  0.41 0.52 0.84 0.76 0.81]
 [0.66 0.93 0.91 0.62 0.11 0.17]]
[False False False False False  True False False]


In [59]:
# 7. NumPy Methods
avg_score_of_employees = performance_matrix.mean(axis=1)
avg_score_of_months = performance_matrix.mean(axis=0)
max_performance = performance_matrix.max()
min_performance = performance_matrix.min()

# axis=1 → satırlar boyunca işlem yapar. Her satirin yani calisanin ortalamasini alir
# axis=0 → sütunlar boyunca işlem yapar. Her sütunun yani ayin ortalamasini alir.

print(f"Average Scores of Employee: {avg_score_of_employees}")
print(f"Average Scores of Months: {avg_score_of_months}")
print(f"Max Scores of Employee: {max_performance}")
print(f"Min Scores of Employee: {min_performance}")

Average Scores of Employee: [50.83333333 28.16666667 43.83333333 36.33333333 61.         55.16666667
 69.         56.66666667]
Average Scores of Months: [58.375 44.875 61.125 54.375 36.5   45.5  ]
Max Scores of Employee: 98
Min Scores of Employee: 3


In [60]:
# 8. NumPy series methods
reshaped_matrix = performance_matrix.reshape(4,12)
transposed_matrix = performance_matrix.transpose()
flattened_matrix = performance_matrix.flatten()

print(reshaped_matrix)
print(transposed_matrix)
print(flattened_matrix)

[[56 25 74 45  7 98 82  6 22 49  5  5]
 [ 3 63 96 38 10 53 92 20 17 57 21 11]
 [16 59 40 92 65 94 72 52 97  8 97  5]
 [80 41 52 84 76 81 66 93 91 62 11 17]]
[[56 82  3 92 16 72 80 66]
 [25  6 63 20 59 52 41 93]
 [74 22 96 17 40 97 52 91]
 [45 49 38 57 92  8 84 62]
 [ 7  5 10 21 65 97 76 11]
 [98  5 53 11 94  5 81 17]]
[56 25 74 45  7 98 82  6 22 49  5  5  3 63 96 38 10 53 92 20 17 57 21 11
 16 59 40 92 65 94 72 52 97  8 97  5 80 41 52 84 76 81 66 93 91 62 11 17]


In [71]:
# General Performance Summary
best_employee_index = avg_score_of_employees.argmax()
highest_month_average_index = avg_score_of_months.argmax()
general_average = performance_matrix.mean()

print(f"Best Employee: Employee{best_employee_index + 1}")
print(f"Highest Month: Month{highest_month_average_index + 1}")
print(f"General Average Performance: {general_average}")

Best Employee: Employee7
Highest Month: Month3
General Average Performance: 50.125
